abercompsoc/blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from abercompsoc.blog.views import BlogDetailView, BlogTableView
from abercompsoc.events.views import EventList, EventDetail

app_name = "abercompsoc.blog"

urlpatterns = [
    path("", BlogTableView.as_view(), name="blog_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        BlogDetailView.as_view(),
        name='blog_detail',
    ),

]

abercompsoc/events/urls.py
from django.urls import path
from django.views.generic import RedirectView

from abercompsoc.events.views import EventList, EventDetail

app_name = "abercompsoc.events"

urlpatterns = [
    path("", view=RedirectView.as_view(pattern_name="events:future_event_list", permanent=True), name="event_list"),
    path("upcoming/", view=EventList.as_view(), name="future_event_list"),
    path("<int:event_id>/", view=EventDetail.as_view(), name="event_detail"),

]

abercompsoc/users/urls.py
from django.urls import path

from abercompsoc.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_delete_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path('~delete/', view=user_delete_view, name="delete"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

abercompsoc/voting/urls.py
from django.urls import path

from abercompsoc.voting.views import ElectionList, UserElectionDetails, UserElectionOptionVote, \
    UserElectionOptionUpdate, UserElectionOptionDelete

app_name = "abercompsoc.voting"

urlpatterns = [
    path("", view=ElectionList.as_view(), name="election_lst"),
    path("<int:election_id>/", view=UserElectionDetails.as_view(), name="election_details"),
    path("<int:election_id>/<int:option_id>/vote/", view=UserElectionOptionVote.as_view(), name="election_option_vote"),
    path("<int:election_id>/run/", view=UserElectionOptionUpdate.as_view(), name="election_option_update"),
    path("<int:election_id>/run/delete", view=UserElectionOptionDelete.as_view(), name="election_option_delete"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("abercompsoc.users.urls", namespace="users"),
    ),

    path(
        "accounts/",
        include("allauth.urls")
    ),
    path(
        "voting/",
        include("abercompsoc.voting.urls", namespace="voting")
    ),
    path(
        "events/",
        include("abercompsoc.events.urls", namespace="events")
    ),
    path(
        "blog/",
        include("abercompsoc.blog.urls", namespace="blog")
    ),

    path("markdownx/", include('markdownx.urls')),


                  # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

abercompsoc/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from markdownx.models import MarkdownxField


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField()
    body = MarkdownxField()
    post_date = models.DateTimeField(auto_now_add=True, verbose_name="Post Date")
    modified = models.DateTimeField(null=True, verbose_name="Modified")
    posted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, verbose_name="Posted by", on_delete=models.SET_NULL)
    allow_comments = models.BooleanField(default=True, verbose_name="Allow Comments")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug,
            'year': '%04d' % self.post_date.year,
            'month': '%02d' % self.post_date.month,
            'day': '%02d' % self.post_date.day,
        }

        return reverse('blog:blog_detail', kwargs=kwargs)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', verbose_name="Post",
        on_delete=models.CASCADE)

    bodytext = models.TextField(verbose_name="Message")

    post_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Post date")

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="User", related_name='comment_user',
        on_delete=models.CASCADE)

    def __str__(self):
        return self.bodytext

abercompsoc/events/models.py
from enum import Enum

from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import DateTimeRangeField
from django.db.models import Model, CharField, ManyToManyField, ForeignKey, CASCADE, IntegerField, TextField, \
    DateTimeField
from django.urls import reverse

User = get_user_model()


class Event(Model):

    event_name = CharField(max_length=255)
    date = DateTimeRangeField()
    attendees = ManyToManyField(User, through="events.UserEventAssociation")
    max_attendees = IntegerField(null=True)
    description = TextField()
    created = DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse("events:event_detail", kwargs={"event_id": self.id})


class EventTiming(Model):
    event = ForeignKey(Event, on_delete=CASCADE)
    details = TextField()
    time = DateTimeField()


class UserEventAssociationType(Enum):
    NA = "NoAssociation"
    IN = "Interested"
    WA = "WantingToAttend"
    WL = "Waiting"
    AT = "Attending"


class UserEventAssociation(Model):
    """
    A many to many linking table, which also s tores the users association to the event, such as
    if they are are attending, or are interested etc
    """

    event = ForeignKey(Event, on_delete=CASCADE)
    user = ForeignKey(User, on_delete=CASCADE)
    info = CharField(max_length=2, choices=[(i, i.value) for i in UserEventAssociationType], default="NA")
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

abercompsoc/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, Model, ManyToManyField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    roles = ManyToManyField("users.Role")

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def __str__(self):
        if self.get_full_name() != "":
            return self.get_full_name()
        return super(User, self).__str__()

    def is_aber_student(self):
        return self.emailaddress_set.filter(verified=True, email__endswith="@aber.ac.uk").exists()


class Role(Model):
    name = CharField("Role Name", max_length=255)

    def __str__(self):
        return self.name.title()

abercompsoc/blog/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from abercompsoc.blog.models import Comment


class UserCommentForm(forms.ModelForm):

    bodytext = MarkdownxFormField()

    class Meta:
        model = Comment
        fields = ["bodytext"]

abercompsoc/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

abercompsoc/blog/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import DetailView, DateDetailView
from django_tables2 import SingleTableView

from abercompsoc.blog.forms import UserCommentForm
from abercompsoc.blog.models import Post, Comment
from abercompsoc.blog.tables import BlogTable


class BlogDetailView(DateDetailView):
    model = Post
    date_field = 'post_date'
    month_format = '%m'

    def get_queryset(self):
        queryset = super(BlogDetailView, self).get_queryset()
        return queryset.select_related()

    def post(self, request, *args, **kwargs):
        self.object = post = self.get_object()
        if request.user.is_authenticated:
            form = UserCommentForm(request.POST)
        else:
            return HttpResponseForbidden()
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect(post.get_absolute_url())
        context = self.get_context_data(object=post)
        context['comment_form'] = form
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        form = UserCommentForm()

        context = {
            'comment_form': form,
            'comments': Comment.objects.filter(post=self.object.id).select_related()
        }
        return super(BlogDetailView, self).get_context_data(**context)


class BlogTableView(SingleTableView):
    table_class = BlogTable
    model = Post

abercompsoc/events/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView
from django_tables2 import SingleTableView

from abercompsoc.events.models import Event
from abercompsoc.events.tables import EventTable


class EventList(SingleTableView):
    model = Event
    table_class = EventTable
    template_name = "events/event_list.html"


class EventDetail(DetailView):
    model = Event
    pk_url_kwarg = "event_id"

abercompsoc/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, DeleteView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserDeleteView(LoginRequiredMixin, DeleteView):

    model = User

    def get_success_url(self):
        return reverse("home")

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_delete_view = UserDeleteView.as_view()


class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    model = User
    fields = ["first_name", "last_name"]
    success_message = "Your profile has been updated!"
    
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

abercompsoc/voting/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView
from django_tables2 import SingleTableView, SingleTableMixin

from abercompsoc.voting.models import Election, UserElectionOption
from abercompsoc.voting.tables import ElectionTable, UserElectionOptionTable


class ElectionList(SingleTableView):
    model = Election
    table_class = ElectionTable
    template_name = "voting/elections_list.html"

    def get_table_kwargs(self):
        kwargs = super(ElectionList, self).get_table_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class UserElectionDetails(SingleTableMixin, DetailView):
    model = Election
    table_class = UserElectionOptionTable
    template_name = "voting/election_details.html"
    pk_url_kwarg = "election_id"

    def get_table_data(self):
        return self.get_object().userelectionoption_set.all()


class UserElectionOptionUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UserElectionOption
    template_name = "voting/option_details.html"
    fields = ["manifesto"]
    success_message = "Your manifesto has been updated!"

    def get_object(self, queryset=None):
        instance, _ = self.model.objects.get_or_create(runner=self.request.user, election_id=self.kwargs.get("election_id"))
        return instance

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class UserElectionOptionDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = UserElectionOption
    template_name = "voting/option_confirm_delete.html"
    success_message = "You are no longer running in this election"

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, runner=self.request.user, election_id=self.kwargs.get("election_id"))

    def get_success_url(self):
        return reverse("voting:election_details", kwargs={"election_id":self.kwargs.get("election_id")})


class UserElectionOptionVote(LoginRequiredMixin, View):

    def post(self, *args, **kwargs):
        election_id = self.kwargs.get("election_id")
        option = get_object_or_404(UserElectionOption, id=self.kwargs.get("option_id"), election__id=election_id)
        election = get_object_or_404(Election, id=election_id)
        
        # Check if the user has voted in this election
        if election.can_vote(self.request.user):
            self.vote_for_election_option(election, option)
        else:
            if self.request.user.election_set.filter(id=election_id).exists():
                messages.add_message(self.request, messages.ERROR, 'You have already voted in this election.')
            elif not election.is_open():
                messages.add_message(self.request, messages.ERROR, 'The selected election is currently not open ')
            elif not self.request.user.is_aber_student() and election.aber_only:
                messages.add_message(self.request, messages.ERROR, 'This election requires you to have a verified '
                                                                   '@aber.ac.uk email address')
            else:  # If we reach this point, then you should look for any extra variables added in election.can_vote
                messages.add_message(self.request, messages.ERROR, 'Something Happened!')
                from sentry_sdk import capture_message
                capture_message("A user could not vote, but we couldn't work out why", level="Error")
        return redirect(election.get_absolute_url())

    def vote_for_election_option(self, election, option):
        """
        Vote for Allows a user to vote for an election option, without checking if its valid beforehand
        :param election: The election to vote in
        :param option: The option to vote for
        """
        election.voters.add(self.request.user)
        option.votes = option.votes + 1
        messages.add_message(self.request, messages.SUCCESS, 'Your vote has been placed.')
        option.save()
        election.save()

abercompsoc/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

abercompsoc/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AberCompSoc{% endblock title %} | AberCompSoc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-16x16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-32x32.png' %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-96x96.png' %}" sizes="96x96">


    {% block css %}
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">
          <img style="height: 2em" class="img-fluid mr-2" src="{% static "images/logos/abercompsoc_icon.svg" %}" alt="Aber Comp Soc Logo">
          AberCompSoc</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% with request.resolver_match.url_name as url_name %}
            {% with request.resolver_match.namespace as namespace %}

            <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if url_name == 'about' %}active{% endif %}">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>

            <li class="nav-item {% if namespace == 'voting' %}active{% endif %}">
              <a class="nav-link" href="{% url 'voting:election_lst' %}">Elections</a>
            </li>
            <li class="nav-item {% if namespace == 'events' %}active{% endif %}">
              <a class="nav-link" href="{% url 'events:event_list' %}">Events</a>
            </li>
            <li class="nav-item {% if namespace == 'blog' %}active{% endif %}">
              <a class="nav-link" href="{% url 'blog:blog_list' %}">News</a>
            </li>

            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item mr-auto">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          {% endwith %}
          {% endwith %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
          {% endfor %}
      {% endif %}
      {% block content %}
        <p>If you see this, then you need to use block content</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Vendor dependencies bundled as one file-->
      <script src="https://browser.sentry-cdn.com/4.4.2/bundle.min.js" crossorigin="anonymous"></script>
      <script>
        Sentry.init({ dsn: 'https://e85beacf31b148778a97fa6ca70531ca@sentry.io/1360494' });
      </script>

      <script src="{% static 'js/vendors.js' %}"></script>
      
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 